"""Extract enemy attack hit timings from the FModel JSON dump.

For every enemy GA with a Montage, find the first weapon/melee trace notify
(the damage window start) and emit a Lua table: GA class name -> seconds from
montage start to first hit.

Output: my-mods/AutoParry/AutoParry/Scripts/timings.lua
"""
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(REPO, "Atlas", "Content")
GA_DIRS = [
    os.path.join(CONTENT, "Blueprints", "Enemies"),
    os.path.join(CONTENT, "Blueprints", "Abilities"),
]
OUT = os.path.join(REPO, "my-mods", "WFQoL", "WFQoL", "Scripts", "timings.lua")

TRACE_MARKERS = ("WeaponTrace", "MeleeTrace", "AnimNotifyState_Trace", "DamageTrace")


def load(path):
    try:
        with open(path, encoding="utf8") as f:
            return json.load(f)
    except Exception:
        return None


def obj_path_to_file(obj_path):
    # 'Atlas/Content/Characters/.../M_SnS_Atk_Cleave.21' -> repo json path
    if not obj_path:
        return None
    base = obj_path.rsplit(".", 1)[0]
    if not base.startswith("Atlas/Content/"):
        return None
    return os.path.join(REPO, base.replace("/", os.sep) + ".json")


def first_trace_time_in_sequence(seq_path):
    """Return earliest trace-notify time within an AnimSequence, or None."""
    data = load(seq_path)
    if not data:
        return None
    best = None
    for x in data:
        if x.get("Type") != "AnimSequence":
            continue
        for n in x.get("Properties", {}).get("Notifies", []):
            cls = ((n.get("NotifyStateClass") or {}).get("ObjectName")) or (
                (n.get("Notify") or {}).get("ObjectName")
            ) or ""
            if any(m in cls for m in TRACE_MARKERS):
                t = n.get("LinkValue") or n.get("TriggerTimeOffset") or 0.0
                if best is None or t < best:
                    best = t
    return best


def first_hit_time_for_montage(mont_path):
    data = load(mont_path)
    if not data:
        return None
    for x in data:
        if x.get("Type") != "AnimMontage":
            continue
        props = x.get("Properties", {})

        # trace notifies directly on the montage
        best = None
        for n in props.get("Notifies", []):
            cls = ((n.get("NotifyStateClass") or {}).get("ObjectName")) or (
                (n.get("Notify") or {}).get("ObjectName")
            ) or ""
            if any(m in cls for m in TRACE_MARKERS):
                t = n.get("LinkValue") or n.get("TriggerTimeOffset") or 0.0
                if best is None or t < best:
                    best = t
        if best is not None:
            return best

        # otherwise: earliest trace across referenced sequences, mapped to montage time
        for tr in props.get("SlotAnimTracks", []):
            for seg in tr.get("AnimTrack", {}).get("AnimSegments", []):
                ref = (seg.get("AnimReference") or {}).get("ObjectPath")
                seq_file = obj_path_to_file(ref)
                if not seq_file:
                    continue
                t = first_trace_time_in_sequence(seq_file)
                if t is None:
                    continue
                start_pos = seg.get("StartPos", 0.0) or 0.0
                anim_start = seg.get("AnimStartTime", 0.0) or 0.0
                rate = seg.get("AnimPlayRate", 1.0) or 1.0
                if t < anim_start:
                    continue
                mont_t = start_pos + (t - anim_start) / rate
                if best is None or mont_t < best:
                    best = mont_t
        return best
    return None


def main():
    timings = {}
    scanned = 0
    for root_dir in GA_DIRS:
        for root, _dirs, files in os.walk(root_dir):
            for fn in files:
                if not fn.startswith("GA_") or not fn.endswith(".json"):
                    continue
                data = load(os.path.join(root, fn))
                if not data:
                    continue
                for x in data:
                    if not x.get("Name", "").startswith("Default__"):
                        continue
                    mont = (x.get("Properties", {}).get("Montage") or {}).get("ObjectPath")
                    mont_file = obj_path_to_file(mont)
                    if not mont_file:
                        continue
                    scanned += 1
                    t = first_hit_time_for_montage(mont_file)
                    if t is not None and t > 0.0:
                        cls = fn[:-5] + "_C"
                        timings[cls] = round(t, 3)

    with open(OUT, "w", newline="\n") as f:
        f.write("-- generated by tools/extract-attack-timings.py - do not hand edit\n")
        f.write("-- GA class name -> seconds from ability montage start to first weapon trace\n")
        f.write("return {\n")
        for k in sorted(timings):
            f.write('    ["%s"] = %s,\n' % (k, timings[k]))
        f.write("}\n")

    vals = sorted(timings.values())
    print("GAs with montage scanned:", scanned)
    print("timings extracted:", len(timings))
    if vals:
        print("min/median/max:", vals[0], vals[len(vals) // 2], vals[-1])
    print("wrote", OUT)


if __name__ == "__main__":
    sys.exit(main())
